---
server:
  sqs:
    enabled: true
    port: 3001
    keys:
      - access_key: DEV_ACCESS_KEY_ID
        secret_key: DEV_SECRET_ACCESS_KEY

  dashboard:
    enabled: true
    port: 3000

  sqlite:
    path: smoothmq.sqlite